### ISSUE TITLE
Review your config.yaml

### ISSUE THREAD

**Issue by Bladefidz** [DevGroup-ru/dotplant2-vagrant#2]
hello @bethrezen.

I've found wrong absolute path on your config.yaml line 71.
`command: 'cd /var/www/dotplant2/applicaiton/ && ./yii background/tasks'`

I think it must be:
`command: 'cd /var/www/dotplant2/application/ && ./yii background/tasks'`

**Comment by bethrezen** [comment]
Yeah, you are wright. Can you make PR?

**Comment by Bladefidz** [comment]
Um, sorry just read your comment already. What is PR ?

**Comment by bethrezen** [comment]
@Bladefidz Pull request
