### ISSUE TITLE
Vagrant Authentication failure

### ISSUE THREAD

**Issue by hellvesper** [DevGroup-ru/dotplant2-vagrant#4]
I've got an error during vagrant up process : `Warning: Authentication failure.`. Something wrong with auth keys I think. I'm not very familiar with vagrant and especially with puppet, so can't fix this by myself.

**Comment by ApXaHgheJI** [comment]
+1

**Comment by fourteenmeister** [comment]
+1

**Comment by bethrezen** [comment]
Dudes, years past I understood that vagrant really sucks. I will not fix this and even try. If you fix and send pull request - I'll merge.
